### ISSUE TITLE
Transparency overlay overlapping on images repeatedly and on the contact section. 

### ISSUE THREAD

**Issue by emilylavinskas** [emilylavinskas/portfolio-old#10]
<img width="1179" alt="screen shot 2015-10-13 at 2 37 40 pm" src="https://cloud.githubusercontent.com/assets/6373195/10464540/472c404a-71b8-11e5-901e-82de4d232580.png">

@thomasjbradley 

When I add the transparency overlay to the portfolio pieces, they layer multiple times, so when all are applied, the transparency shows up 6 times over the first image, etc. It also adds the overlay to the contact section but only on the large screen.

``` html
<div class="portfolio-section" id="portfolio">
        <div class="">
            <img class="portfolio-piece" src="images/test-photo.jpg" alt="">
            <div class="overlay"></div>
        </div>
        <div class="">
            <img class="portfolio-piece" src="images/test-photo.jpg" alt="">
            <div class="overlay"></div>
        </div>
        <div class="">
            <img class="portfolio-piece" src="images/test-photo.jpg" alt="">
        </div>
        <div class="">
            <img class="portfolio-piece" src="images/test-photo.jpg" alt="">
        </div>
        <div class="">
            <img class="portfolio-piece" src="images/test-photo.jpg" alt="">
        </div>
        <div class="">
            <img class="portfolio-piece" src="images/test-photo.jpg" alt="">
        </div> 
    </div> 

    <div class="contact-section" id="contact">
        <h2 class="contact-title">Impressed? Let's talk!</h2>
        <div class="contact-icons">
            <a href="mailto:hey@emilylavinskas.ca?Subject=Hi There!" target="_top"><img class="icon-1" src="images/email-icon.svg" alt="email icon"></a>
            <a href="http://behance.net/emilycmyk"><img class="icon-2" src="images/behance-icon.svg" alt="behance icon"></a>
            <a href="https://ca.linkedin.com/in/emilylavinskas"><img class="icon-3" src="images/linkedin-icon.svg" alt="linkedin icon"></a>
            <a href="http://instagram.com/hey.imemily"><img class="icon-4" src="images/instagram-icon.svg" alt="instagram icon"></a>
        </div>
    </div>
```

``` CSS
.portfolio-piece {
    width: 100%;
    position: relative;
}
.overlay {
    background-color: rgba(78, 19, 30, 0.3);
    position: absolute;
    width: 100%;
    height: 100%;
}

.contact-section {
    background-image: url("../images/wood-background.jpg");
    background-repeat: no-repeat;
    background-size: cover;
    overflow: hidden;
    clear: both;
}
```
